### ISSUE TITLE
Python 2.7 tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.container#5]
Since https://github.com/zopefoundation/zope.app.container/actions/runs/2011734335 the tests on Python 2.7 and PyPy2 are broken.

The only differences in the dependencies to the previous runs are:

* ZODB==5.6.0 -> ZODB==5.7.0
* pytz==2021.3 -> pytz==2022.1

I think it is caused by the ZODB release.
IMHO the easiest way to fix this would be to drop Python 2.7 support.

Any other opinions?

**Comment by jamadden** [comment]
The issue is in the 6.1.0 release of zope.publisher from 2022-03-15; reverting to the previous release (6.0.2) fixes it. The 6.1.0 release changes the way requests are decoded:


> Revamp handling of query string and form decoding in BrowserRequest.
>
> The previous approach was to tell underlying libraries to decode inputs using ISO-8859-1, then re-encode as ISO-8859-1 and decode using an encoding deduced from the Accept-Charset request header. However, this didn’t make much conceptual sense (since Accept-Charset defines the preferred response encoding), and it made it impossible to handle cases where the encoding was specified as something other than ISO-8859-1 in the request (which might even be on a per-item basis, in the case of multipart/form-data input).
>
> We now only perform the dubious Accept-Charset guessing for query strings; in other cases we let multipart determine the encoding, defaulting to UTF-8 as per the HTML specification. For cases where applications need to specify some other default form encoding, BrowserRequest subclasses can now set default_form_charset.
>
> See issue 65.

The now-failing test was somewhat tightly coupled to the old behaviour:

https://github.com/zopefoundation/zope.app.container/blob/5a472543abe39f0d120c8aff4616d24c17e91eb7/src/zope/app/container/browser/tests/test_contents_functional.py#L367-L402

**Comment by jamadden** [comment]
If we change https://github.com/zopefoundation/zope.app.container/blob/5a472543abe39f0d120c8aff4616d24c17e91eb7/src/zope/app/container/browser/tests/test_contents_functional.py#L396

to be `….encode('latin-1')`, then the Python 2 tests are fixed but the Python 3 tests break with the error that Python 2 used to get. I haven't been able to find a combination of headers and encoding that work for both versions. 

I wonder if we're looking at another issue in the underlying `multipart` library? 

/cc @cjwatson

**Comment by icemac** [comment]
No answer from @cjwatson so I am going to drop Python 2 support as Python 3 is fine.

**Comment by cjwatson** [comment]
Sorry, I missed this.  The test looks dubious in principle based on the rationale I laid out in my `zope.publisher` change, but we're probably well into diminishing returns for investigating Python 2 issues at this point, so dropping it seems reasonable.
